# Welcome to Jekyll!
title: Hello, world! I'm Konstantin Soima
email: konstantin.soyma@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
domain: konstantin-soima.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://konstantin-soima.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /konstantin-soima.github.io/      # place folder name if the site is served in a subfolder
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Night_Maniac
github_username:  konstantin-soima

site-twitter: Night_Maniac #if your site has a twitter account, enter it here

# Author Settings
author: Konstantin Soima # add your name
author-img: photo_for_cv.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: Night_Maniac # add your Twitter handle
social-facebook: konstantin.soyma # add your Facebook handle
social-github: konstantin-soima # add your Github handle
social-linkedin: konstantin-soima # add your Linkedin handle
social-email: konstantin.soyma@gmail.com # add your Email address



# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-twitter-plugin
#  - jekyll-feed
# надо ещё твиттер прихуячить

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
